package edu.ntnu.idatt2003.idatt2003boardgame.view.elements;

import edu.ntnu.idatt2003.idatt2003boardgame.model.Player;
import edu.ntnu.idatt2003.idatt2003boardgame.model.observer.GameModelObserver;
import javafx.application.Platform;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;

/**
 * A JavaFX VBox containing a TextArea that acts as a game console,
 * observing and displaying game events.
 * 
 * @author Bjørn Adam Vangen
 * Constructor partially generated by Gemini AI in order to save time
 */
public class GameConsoleView extends VBox implements GameModelObserver {

    private final TextArea consoleArea;

    /**
     * Creates a new GameConsoleView.
     */
    public GameConsoleView() {
        this.consoleArea = new TextArea();
        this.consoleArea.setEditable(false);
        this.consoleArea.setWrapText(true);
        this.consoleArea.getStyleClass().add("game-console-area");

        Label title = new Label("Game Log");
        title.getStyleClass().add("game-console-title");

        VBox.setVgrow(consoleArea, Priority.ALWAYS);

        this.getChildren().addAll(title, consoleArea);
        this.getStyleClass().add("game-console");
        this.setSpacing(5);
    }

    private void appendText(String message) {
        Platform.runLater(() -> {
            consoleArea.appendText(message + "\n");
            consoleArea.setScrollTop(Double.MAX_VALUE);
        });
    }

    /**
     * Called when a dice roll occurs in the game.
     * This implementation appends a message indicating the dice roll value to the console area.
     *
     * @param value The value rolled on the dice.
     */
    @Override
    public void onDiceRolled(int value) {
        appendText("Dice rolled: " + value);
    }

    /**
     * Called when a player moves to a new position on the board.
     * This implementation appends a message indicating the player's name and their new position
     * to the console area.
     *
     * @param player The player who moved.
     * @param newPosition The new tile number (typically 1-based) the player has moved to.
     */
    @Override
    public void onPlayerMoved(Player player, int newPosition) {
        appendText(player.getName() + " moved to square: " + newPosition);
    }

    /**
     * Called when the game turn changes to a new player.
     * This implementation appends a message indicating whose turn it is now to the console area.
     *
     * @param newPlayer The player whose turn it is now.
     */
    @Override
    public void onTurnChanged(Player newPlayer) {
        appendText("It is now " + newPlayer.getName() + "'s turn!");
    }

    /**
     * Called when a player wins the game.
     * This implementation appends a congratulatory message with the winner's name to the console area.
     *
     * @param winner The player who has won the game.
     */
    @Override
    public void onGameWon(Player winner) {
        appendText("Congratulations " + winner.getName() + ", you won the game!");
    }

    /**
     * Returns the root JavaFX Node for this console view component.
     * In this case, it returns the {@link VBox} instance itself.
     *
     * @return The VBox that contains the game console UI elements.
     */
    public VBox getViewNode() {
        return this;
    }
}